---
- name: Install units for ansible-pull
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    src: "{{ item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: Enable ansible-pull timer
  become: true
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: true
