#!/usr/bin/env bash
# using ideas from https://github.com/punchagan/ansible-system-setup/blob/main/bootstrap to set up mine

set -euo pipefail

URL="https://github.com/dabrown645/ansible-master.git"

# Install Ansible (ansible-pull and Git
if $(type -P apt > /dev/null) ; then
    sudo apt update
    sudo apt upgrade -y
    (which ansible-pull >/dev/null \
        && which python3 >/dev/null \
        && which git >/dev/null) || (sudo apt install -y git python3 python3-psutil ansible openssh-server sshpass) \
        && systemctl enable sshd
elif $(type -P pacman > /dev/null) ; then
    sudo pacman -Syu --noconfirm
    (which ansible-pull >/dev/null \
         && which git >/dev/null) || (sudo pacman --noconfirm -Syu ansible git sshpass) \
        && systemctl enable --now sshd
elif $(type -P zypper >/dev/null); then
    (which ansible-pull && which git) || (sudo zypper install -y ansible git sshpass)
else
    echo "OS type not supported"
fi

# Create ansible log directory
# NOTE: Ensure it i the same as in the log path in Ansible.cfg
mkdir -p /var/log

branch=${1:-main}
if  [[ ${#} -ge 1 ]] ; then
    shift
fi

echo "sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-dabrown ~/Public" > ~/mnt.sh
chmod +x ~/mnt.sh

ansible-pull -U https://github.com/dabrown645/ansible-master.git -K -k -i "$(uname -n)," --diff --checkout ${branch} ${@}
