---
- hosts: all
  tasks:
    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ hostvars[inventory_hostname].pull_groups }}"
      changed_when: false

- import_playbook: playbook.yml
