- hosts: laptop
  tasks:
    - debug:
        msg: "I'm in group 'mygroup'"

- hosts: onlypop
  tasks:
    - debug:
        msg: "I'm in group 'onlypop'"

- hosts: onlysuse
  tasks:
    - debug:
        msg: "I'm in group 'onlysuse'"

- hosts: onlygaruda
  tasks:
    - debug:
        msg: "I'm in group 'onlygaruda'"

  # - name: configure ansible-pull
  #   hosts: all
  #   roles:
  #     - role: ansible-pull
  #       ansible_pull_url: https://github.com/dabown645/ansible-master
