---
- name: Debuging
  ansible.builtin.debug:
    msg:
      - "{{ user }}"

- name: Ensure user.group exists
  ansible.builtin.group:
    name: "{{ user.group }}"
    state: present
    system: "{{ user.system | default(false) }}"
  when: user.name is defined

- name: Ensure group in user.groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: "{{ user.system | default(false) }}"
  loop: "{{ user.groups }}"
  when: user.groups

- name: Process users
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.comment | default('Unknown User') }}"
    shell: "{{ user.shell | default('/usr/bin/bash') }}"
    group: "{{ user.group }}"
    groups: "{{ user.groups }}"
    append: "{{ user.append | default(true) }}"
    system: "{{ user.system | default(false) }}"
    createhome: "{{ user.createhome | default(true) }}"
    home: "{{ user.home | default( '/home/' + user.name) }}"
    password:  "{{ user.password | default(omit) }}"

      # sddm doesn't support changing password
      #- name: Force change password on login
      #  ansible.builtinn.shell:
      #    cmd: chage -d 0 "{{ user.name }}"
