---
# Archlinux specific configuration
- name: Remove unwanted packages from system
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ base_pkgs_remove }}"

- name: Install base groups and packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_groups_install }}"
    - "{{ base_pkgs_install }}"

- name: Install desttop specific packages
  ansible.builtin.include_tasks: "{{ desktop_env }}.yml"
