---
# Archlinux specific configuration
- name: Debug info
  ansible.builtin.debug:
    var: base_groups_install

- name: Get desktop environment
  ansible.builtin.shell: |
    wmctrl -m | head 1 | cut -f 2 -d " " | tr [A-Z] [a-z]
  register: desktop_env

- name: Set destop env fact
  ansible.builtin.set_fact:
    mydesktop_env: "{{ desktop_env }}"


- name: Remove unwanted packages from system
  community.general.pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ base_pkgs_remove }}"

- name: Install base groups and packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_groups_install }}"
    - "{{ base_pkgs_install }}"

- name: Debug info when
  ansible.builtin.debug:
    var: ansible_env

- name: Install base plasma-kde groups packages 
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_plasma_kde_install }}"
  when: desktop_env == "kwin"
