---
- name: Set ENCRYPT_METHOD SHA512
  ansible.builtin.lineinfile:
    path: "{{ logindefs }}"
    regexp: "^#?ENCRYPT_METHOD"
    line: "ENCRYPT_METHOD SHA512"

- name: Update UID_MIN
  ansible.builtin.lineinfile:
    path: "{{ logindefs }}"
    regexp: "^#?UID_MIN"
    line: "UID_MIN         2000"

- name: Update GID_MIN
  ansible.builtin.lineinfile:
    path: "{{ logindefs }}"
    regexp: "^#?GID_MIN"
    line: "GID_MIN         2000"

- name: Add users
  ansible.builtin.include_tasks: addusers.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
