---
- name: Install base plasma-kde groups packages 
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_plasma_kde_install }}"

- name: Install latte-dock
  ansible.builtin.package:
    name: latte-dock
    state: present
