---
- name: Load a variable file based on OS type info
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution | replace(' ', '_') | lower }}_{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution | replace(' ', '_') | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - 'vars'

- name: Remove unwanted packages from system
  ansible.builtin.package:
    name: "{{ base_pkgs_remove }}"
    state: absent

- name: Install base groups and packages
  ansible.builtin.package:
    name: "{{ base_pkgs_install }}"
    state: present

- name: Install base pip packages
  ansible.builtin.include_tasks: pippkgs.yml

- name: Install desttop specific packages
  ansible.builtin.include_tasks: "{{ desktop_env }}.yml"

- name: Configure locale
  ansible.builtin.include_tasks: locale.yml

- name: Add users
  ansible.builtin.include_tasks: configusers.yml

- name: Install microcode if requested
  ansible.builtin.include_tasks: microcode.yml
