---
- name: Debug info
  ansible.builtin.debug:
    msg:
      - "{{ ansible_os_family | lower }}"
      - "{{ ansible_distribution | replace(' ', '_') | lower }}"
      - "{{ ansible_distribution_version | lower }}"

- name: Load a variable file based on OS type info
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution | replace(' ', '_') | lower }}_{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution | replace(' ', '_') | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - 'vars'

- name: Remove unwanted packages from system
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ base_pkgs_remove }}"

- name: Install base groups and packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_pkgs_install }}"

- name: Install desttop specific packages
  ansible.builtin.include_tasks: "{{ desktop_env }}.yml"

- name: Configure locale
  ansible.builtin.include_tasks: locale.yml

- name: Configure ntp
  ansible.builtin.include_tasks: ntp.yml
