---
- name: Install microcode if requested
  block:
    - name: Install AMD micro code
      ansible.builtin.package:
        name: "{{ amd_microcode }}"
        state: present
      when: system.processor == 'amd'

    - name: Install Intel micro code
      ansible.builtin.package:
        name: "{{ intel_microcode }}"
        state: present
      when: system.processor == 'intel'
