---

- name: Install ntp daemon
  ansible.builtin.package:
    name: ntp
    state: present
  register: install
  until: install is success
  retries: 10
  delay: 2
    # notify: rkhunter propupdate

- name: Configure us atomic clocks
  ansible.builtin.copy:
    src: ntp.conf
    dest: /etc/
  notify:
    - restart ntpd

- name: Make sure ntpd is stopped
  ansible.builtin.service:
    name: ntpd
    state: stopped
    enabled: true

- name: Sync time with US ntp servers
  ansible.builtin.command: ntpdate us.pool.ntp.org

- name: Start ntpd back up
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true

- name: Sync time to hwclock
  ansible.builtin.command: hwclock --systohc
