---
- name: Converge
  no_log: false
  hosts: all
  pre_tasks:
    #    - name: Wait for systemd to complete initialization.
    #  ansible.builtin.command: systemctl is-system-running     # noqa: command-instead-of-module
    #  register: systemctl_status
    #  until: >-
    #    "running" in systemctl_status.stdout or "degraded" in
    #    systemctl_status.stdout
    #  retries: 30
    #  delay: 5
    #  when:
    #    - ansible_service_mgr == "systemd"
    #  changed_when: false

    - name: Update package cache (yum)
      ansible.builtin.yum:
        update_cache: true
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
      when:
        - ansible_os_family | lower == "redhat"
        - ansible_distribution_major_version < 8

    - name: Update package cache (dnf)
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
      when:
        - ansible_os_family | lower == "redhat"
        - ansible_distribution_major_version >= 8

    - name: Update package cache (apt)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
      when:
        - ansible_os_family | lower == "debian"

  roles:
    - role: dabrown645.system.upgrade
